export const SET_RESULT = 'SET_RESULT'
export const SET_UNITS = 'SET_UNITS'
export const ADD_FAVORITES = 'ADD_FAVORITES'
export const ERROR = 'ERROR'
export const GET_CITY = 'GET_CITY'
export const DEL_FAV = 'DEL_FAV'